### ISSUE TITLE
Architecture Development

### ISSUE THREAD

**Issue by tms-epcc** [lsst-uk/ARCHIVE-lasair-lsst#69]
- [x]  Build installable lasair client library "pip install lasair"
- [x] Make sample Jupyter notebooks in Google Colab
- [x] Decommission old Jupyter at RAL
- [x] Decide how to handle Solar System objects and one-night stands
- [x] Offer Kafka streams to customers -- Zooniverse, Tides, etc
- [ ] Experiment with dask for data mining, timing and profiling  (@RoyWilliams)
    - see also [Define and document a few sample "big data" tasks](https://app.zenhub.com/workspaces/lasair-5f75d02d91823488d74ec3f8/issues/lsst-uk/lasair/154) below
    - waiting for new Somerville before progressing
- [ ] Modify software to be survey-agnostic (@RoyWilliams)). This is really a goal for a future cycle.
- [x] Experiment with connection to forced photometry light curves at IPAC (@RoyWilliams)
see https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2719612929/ZTF+Forced+photometry+and+Lasair
- [x] Setup Vault for secrets (@gpfrancis)
- [x] Convert Lasair software to use Vault (@genghisken, @RoyWilliams)
see for example https://github.com/lsst-uk/lasair-lsst/blob/master/filter/settings.py.j2
- [x] [Fully automate the creation of cluster VMs](https://app.zenhub.com/workspaces/lasair-5f75d02d91823488d74ec3f8/issues/lsst-uk/lasair-lsst/40) see below
