### ISSUE TITLE
Review and set up resilience plan

### ISSUE THREAD

**Issue by tms-epcc** [lsst-uk/ARCHIVE-lasair-lsst#74]
- [x] Make backup systems for MySQL 
-- replaced by Galera that is self-backed up
- [x] Make backup systems for Cassandra
-- temporary backup setup , will be replaced when data imported and new hardware in place
-- exploring configuration changes to allow the machines to identified by hostname in Cassandra. This will make backup quicker and easier.
- [x] Set up Galera or other RDB with resilience and parallelism. See @genghisken 's [wiki blog](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2606333953/Lasair+Galera+Installation)
- [x] Monitor Lasair pipeline and webserver and immediate alert of humans with problems [code here](https://github.com/lsst-uk/lasair-lsst/blob/master/utility/slack_webhook.py)
- [x] Elaborate emergency response plans ([detail here](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2051768321/Lasair+Emergency+Response))
- [x] Build startup document for each subsystem (@RoyWilliams , @gpfrancis, @genghisken)
     * Progress made with this see [Lasair Principles of Operation](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2763161628/Lasair+Principles+of+Operation)
     * see also [Build and document the control of multiple clusters](https://app.zenhub.com/workspaces/lasair-5f75d02d91823488d74ec3f8/issues/lsst-uk/lasair-lsst/39) below

**Comment by thespacedoctor** [comment]
[Here's a tutorial](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2507243525/Using+Slack+as+a+Destination+for+System+Monitoring+Alerts) on how to use slack for monitoring alerts. Hope it's useful.

**Comment by RoyWilliams** [comment]
Heres the first few places where the code wants to send a slack message

ingest/ingestBatch: cannot connect to kafka 
https://github.com/lsst-uk/lasair-lsst/blob/master/ingest/ingestBatch.py#L293

ingest/ingestBatch: cannot connect to cassandra 
https://github.com/lsst-uk/lasair-lsst/blob/master/ingest/ingestBatch.py#L285

ingest/ingestBatch: cannot produce kafka 
https://github.com/lsst-uk/lasair-lsst/blob/master/ingest/ingestBatch.py#L270

filter/refresh: cannot clear local database
https://github.com/lsst-uk/lasair-lsst/blob/master/filter/refresh.py#L11

filter/ingestStream: cannot connect to kafka
https://github.com/lsst-uk/lasair-lsst/blob/master/filter/ingestStreamThreaded.py#L146

filter/ingestStream: cannot connect to local database
https://github.com/lsst-uk/lasair-lsst/blob/master/filter/ingestStreamThreaded.py#L139

filter/ingestStream: database insert failed for local database
https://github.com/lsst-uk/lasair-lsst/blob/master/filter/ingestStreamThreaded.py#L88

filter/insert_query: cannot compute HTM index
https://github.com/lsst-uk/lasair-lsst/blob/master/filter/insert_query.py#L222

filter/filter: cannot connect to local database
https://github.com/lsst-uk/lasair-lsst/blob/master/filter/filter.py#L61

filter/check_alerts_watchlists: cannot read watchlist cache directory
https://github.com/lsst-uk/lasair-lsst/blob/master/filter/check_alerts_watchlists.py#L35

filter/check_alerts_areas
https://github.com/lsst-uk/lasair-lsst/blob/master/filter/check_alerts_areas.py#L25

filter/filter: cannot build CSV from local database
https://github.com/lsst-uk/lasair-lsst/blob/master/filter/filter.py#L92

filter/filter: cannot copy CSV to master database node
https://github.com/lsst-uk/lasair-lsst/blob/master/filter/filter.py#L105

filter/filter: cannot ingest CSV on master database node
https://github.com/lsst-uk/lasair-lsst/blob/master/filter/filter.py#L109

filter/run_active_queries: cannot connecto to local database
https://github.com/lsst-uk/lasair-lsst/blob/master/filter/run_active_queries.py#L178

filter/run_active_queries: cannot send email
https://github.com/lsst-uk/lasair-lsst/blob/master/filter/run_active_queries.py#L114

filter/run_active_queries: cannot produce to public kafka
https://github.com/lsst-uk/lasair-lsst/blob/master/filter/run_active_queries.py#L130

services/TNS/poll_tns: Cannot connect to TNS server
https://github.com/lsst-uk/lasair-lsst/blob/master/services/TNS/poll_tns.py#L216

services/TNS/poll_tns: Cannot connect to master database
https://github.com/lsst-uk/lasair-lsst/blob/master/services/TNS/poll_tns.py#L245

**Comment by thespacedoctor** [comment]
Can I suggest that code to send alerts to slack is not added directly into
the Lasair code-base but used with whatever scheduling software is
employed. Best to keep all systems decoupled for maximum portability and
also makes it much easier to switch out individual components in the future.

A specific setup here could be to use 'monit' to schedule & trigger a task.
It has the ability to send different alerts based on the final status of
the task triggered.

https://mmonit.com/monit/

It is very simple to get setup and running.

**Comment by RoyWilliams** [comment]
Have just put in the alerting mechanism into the Lasair code base
https://github.com/lsst-uk/lasair-lsst/blob/master/utility/slack_webkook.py

**Comment by RoyWilliams** [comment]
```
import os,sys, time
from datetime import datetime
from subprocess import Popen, PIPE
import slack_webhook
import settings

# Lasair runner pattern run a worker process repeatedly. 

# We have a worker program that grabs lots of alerts and processes them
# then does post processing on that batch, using print() to show its status.
# We want to be able to run the worker in test mode, and also use the runner 
# in a screen session to run forever. When we stop the runner, we want the
# worker to finish cleanly.

# The worker may need initial arguments to start, eg time of day
# to decide which kafka topic to read.

# The worker will only run if a lockfile is present. This means the
# runner can be stopped cleanly by deleting the lockfile.

# The worker return code indicates if there are more alerts to read (0)
# or if the worker terminated with no more to read (>0).
# If no more, the runner can wait a while before trying again.

# The stdout is grabbed immediately and can be logged. 
# NOTE the worker process should call sys.stdout.flush() after printing

# If the stdout line starts with ERROR, further action is taken
# to alert the humans

def now():
    # current UTC as string
    return datetime.utcnow().strftime("%Y/%m/%dT%H:%M:%S")

while 1:
    # open the log file
    log = open(settings.LOG_FILE, 'a')

    if os.path.isfile(settings.LOCKFILE):

        # compute the starting conditions
        worker_args = []

        # start the worker in subprocess
        rtxt = 'Starting at ' + now()
        print(rtxt)
        log.write(rtxt + '\n')
        args = ['python', 'worker.py'] + worker_args
        process = Popen(args, stdout=PIPE, stderr=PIPE)

        # fetch lines of printed output
        while 1:
            # when the worker terminates, readline returns zero
            rbin = process.stdout.readline()
            if len(rbin) == 0: break

            # if the worher uses 'print', there will be at least the newline
            rtxt = rbin.decode('ascii').rstrip()
            log.write(rtxt + '\n')
            print(rtxt)

            # scream to the humans if ERROR
            if rtxt.startswith('ERROR'):
                slack_webhook.send(rtxt)

        # close the log and get the return code
        log.close()
        rc = process.wait()
        if rc > 0:
            time.sleep(settings.WAIT_FOR_ALERTS)
    else:
        # wait until the lockfile reappears
        rtxt = 'Waiting for lockfile ' + now()
        print(rtxt)
        log.write(rtxt + '\n')
        time.sleep(settings.WAIT_TO_START)
```

**Comment by gpfrancis** [comment]
Have added build & deployment instructions for the Sherlock wrapper in https://github.com/lsst-uk/lasair-lsst/blob/master/sherlock_wrapper/README.md

Can somebody comment on whether these would be sufficient for somebody else to restart the component or whether more detail is required and, if so, what?

**Comment by tms-epcc** [comment]
14/JUL/21
- @gpfrancis reported that @RoyWilliams and @genghisken had provided comments on the build & deployment instructions for the Sherlock wrapper in https://github.com/lsst-uk/lasair-lsst/blob/master/sherlock_wrapper/README.md
