### ISSUE TITLE
User contributed annotations (FastFinder, Zooniverse) 

### ISSUE THREAD

**Issue by tms-epcc** [lsst-uk/ARCHIVE-lasair-lsst#98]
- [x] Document the [plan of action](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/edit-v2/2723250183)
- [x] Build models and supporting software ( @RoyWilliams  )
- [x] Prototype sprint end October ( @mFulton07, @smarttgit,  @genghisken, @RoyWilliams)
- [x] Modify query builder and checker for annotation queries
- [x] Make annotations available to streaming queries
- [x] Extend API to allow annotation push ( @genghisken, @thespacedoctor)
- [x] Make it easier to develop annotators without waiting for alerts
- [x] Create annotator class which streams annotations immediately

**Comment by tms-epcc** [comment]
@mFulton07 to test in advance of prototype sprint

**Comment by tms-epcc** [comment]
@RoyWilliams completed this.  See pull request https://github.com/lsst-uk/lasair-lsst/pull/123
